### PR TITLE
removes unecessary library references

### LINKED ISSUE #13: Remove references to unused libraries
Lodash
Jokenizer
DynamicQuearyable
Telerik

### PR DESCRIPTION
**Pull request by mathisjay**
resolves #13

### CODE REVIEW

**Comment by david-poindexter** [comment]
Looks like you are starting to get the hang of the git-flow here.  One tweak I'd recommend is to create a new branch in your local repo for the issue being worked on.  So in this case, it would have been a branch called `issue-13`.  Then you can push `issue-13` to your forked (origin) repo and create a pull request from there to `master` on the main DNNCommunity repo.

As the owner/steward/lead on this project, you certainly have the rights to self-merge pull requests, but it is always a good policy (especially when other maintainers/contributors are involved), to request a **Review** by at least one of them.

Hope you don't mind the Git/GitHub tips here.  Since this lives within the DNNCommunity GitHub org, it is important we set a good example for others in the community.  :)

**Comment by mathisjay** [comment]
Thanks!   Keep the tips coming!  Still learning over here 😊

One thing I was struggling with was how to get my origin fork to sync up with upstream before branching locally.  But I think perhaps I just branch locally from upstream:master and then push that branch to origin and the PR from origin to master.  Is that right?

**Comment by david-poindexter** [comment]
@mathisjay there are multiple ways people prefer to do this, but here is my flow every time I work on a new issue.

1. `git checkout master` to switch to my local repo's `master` branch
2. `git branch` to list all branches currently on my local repo
3. `git branch -D <branch-name>` for any branches I want to delete
4. `git pull upstream master` to make sure my local `master` branch is in sync with the upstream `master` branch
5. `git push origin master' to make sure my forked (origin) GitHub `master` branch is in sync with my local and upstream `master` branches
6.  `git checkout -b issue-##` (in your case this would have been `issue-13`) to copy my local `master` branch into a new branch named `issue-##`
7.  Make changes to the code and test locally
8.  `git add .` to stage all changes for local commit (by the way, a `.` should not be used if you only want to stage a subset of files that were changed - for that you can use `git add <file-name>` for each file you want to stage)
9.  `git commit -m "a meaningful message about your commit"` to commit changes to your local repo (For the message, I typically use the title of the GitHub issue I am working on, as this really helps keep things nice and organized for repo owners/maintainers and makes it obvious what was done for the commit.  For more complex issues, requiring multiple commits prior to submitting a pull request, I use more meaning messages related to each commit.)
10. `git push origin issue-##` (in your case this would have been `issue-13`) to push your local repo branch to your forked (origin) GitHub repo
11.  Visit forked (origin) GitHub repo or main (upstream) GitHub repo in your browser to create the pull request (PR).  In the PR description, use the special GitHub keywords mentioned [HERE](https://help.github.com/en/articles/closing-issues-using-keywords) to reference the issue for which this PR relates (in your case something like `Resolves #issue-13`).  This is important for repo owners/maintainers because this allows the referenced issue to be auto-closed upon merge of the pull request.

There are certainly more complex scenarios that come up from time to time, but the above is a good general git-flow for most scenarios.  I hope this helps!

**Comment by mathisjay** [comment]
Very helpful!  Thanks!

**Pull request merged**
